import { Metadata } from 'next';
import { memo } from 'react';
export const metadata: Metadata = {
  title: "E-commerce/users",
  description: "Generated by create next app",
};
const User = () => {
  return (
    <div className="Page min-h-[500px]">
      <h2>Page</h2>
    </div>
  );
};

export default memo(User);