import Image from "next/image";
import { memo } from "react";
import no from "@/assets/noImage.jpg";
import { Metadata } from "next";
import ProductView from "@/components/productView/ProductView";
export const metadata: Metadata = {
  title: "E-commerce/details",
  description: "Generated by create next app",
};
const Detail = async ({ params }: { params: Promise<{ id: string }> }) => {
  const { id } = await params;

  const response = await fetch(`https://api.errorchi.uz/product/${id}`);

  const data = await response.json();
  const info = data?.data;
  const malumot = await fetch("https://api.errorchi.uz/product?limit=4", {
    next: { revalidate: 60 },
  });
  const similar = await malumot.json()
  const similarData = similar?.data?.allProducts
  console.log(similarData);
  

  return (
    <section className="min-h-[800px] ">
      <div className=" container">
        <div className="grid grid-cols-1 py-[30px] mt-[40px] md:grid-cols-2 gap-10 bg-white rounded-2xl  p-6">
          <div className="flex items-center justify-center">
            <Image
              src={
                info?.images?.length
                  ? "https://api.errorchi.uz/product/image/" + info?.images[0]
                  : no
              }
              width={400}
              height={400}
              alt={info?.title || "Product image"}
              className="rounded-xl object-cover shadow-md  h-[530px] w-[440]"
            />
          </div>

          <div className="flex flex-col justify-between">
            <div>
              <h1 className="text-[40px] font-extrabold text-gray-900 mb-2">
                {info?.title}
              </h1>
              <p className="text-lg text-gray-600 mb-4">{info?.description}</p>
              <hr className="bg-[#ddd] border-0 h-[1px]" />

              <ul className="space-y-2 text-gray-700 pt-[70px]">
                <li>
                  <span className="font-semibold">Brand:</span> {info?.brand}
                </li>
                <li>
                  <span className="font-semibold">Category:</span>{" "}
                  {info?.category?.name}
                </li>
                <li>
                  <span className="font-semibold">Stock:</span> {info?.stock}
                </li>
                <li>
                  <span className="font-semibold">Seller:</span>
                  {info?.user?.fname} ({info?.user?.email})
                </li>
              </ul>
            </div>
            <hr className="bg-[#ddd] border-0 h-[1px]" />

            <div className="mt-6 flex items-center gap-[20px]">
              <span className="text-2xl font-bold text-[#000] bg-amber-300 px-[8px]">
                ${info?.price?.toLocaleString()}
              </span>
              <button className="px-20 py-2 rounded-xl bg-[#000] text-white font-medium  transition">
                Buy Now
              </button>
            </div>
          </div>
        </div>
        <div className="pb-[200px]">
          <ProductView data={similarData} />
        </div>
      </div>
    </section>
  );
};

export default memo(Detail);
